apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-efficiency
  resources:
    requests:
      storage: 20Gi
