apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  labels:
    app: app-demo
spec:
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: registry.cn-hangzhou.aliyuncs.com/haoshuwei24/app-demo:v1
      - $patch: replace
