apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-demo
  name: app-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app-demo
  type: ClusterIP
